spring.application.name=fare-service
server.port=8084

# MongoDB configuration
spring.mongodb.uri=${MONGO_URI:${MONGODB_URI:mongodb://localhost:27017/fare_db}}
spring.data.mongodb.uri=${MONGO_URI:${MONGODB_URI:mongodb://localhost:27017/fare_db}}
