spring.application.name=driver-service
server.port=8082
spring.data.mongodb.uri=mongodb+srv://jlmusiclive_db_user:4jR2moJrbRg2xG5C@cluster0.gxaghqa.mongodb.net/driver-service?appName=Cluster0
spring.application.name=driver-service
