spring.application.name=driver-service
server.port=8082

# MongoDB configuration
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/driver_db}
spring.mongodb.uri=${MONGO_URI:${MONGODB_URI:mongodb://localhost:27017/driver_db}}

# SpringDoc OpenAPI / Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
